from pathlib import Path

ROOT = Path(__file__). parent
FILES_DIR = ROOT / 'files'
ICON_PATH = FILES_DIR / 'icon.png'

BIG_FONT_SIZE = 42
MEDIUM_FONT_SIZE = 28
SMALL_FONT_SIZE = 14
TEXT_MARGIN = 10
MINIMUM_WIDHT = 360

PRIMARY_COLOR = '#1e81b0'
DARK_PRIMARY_COLOR = '#16658a'
DARKEST_PRIMARY_COLOR = '#115270'
